### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MarharytaZobacheva** [megzobacheva/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by megzobacheva** [comment]
— I want to rebuild our nation to save America. As one of the most controversial politicians and presidents I promise to make America greater and greater, again and again.
— We will save the American economy, and make America once again a shining city on the hill.
— Melania promised to decorate the Mexican wall we build on Christmas if I win next elections.
Haters may triumph my new presidency.

**Comment by megzobacheva** [comment]
### **Resume**

— I want to rebuild our nation to save America. As one of the most controversial politicians and presidents I promise to make America greater and greater, again and again.
— We will save the American economy, and make America once again a shining city on the hill.
— Melania promised to decorate the Mexican wall we build on Christmas if I win next elections.
Haters may triumph my new presidency.

**Comment by MarharytaZobacheva** [comment]
### **Resume**
— I want to rebuild our nation to save America. As one of the most controversial politicians and presidents I promise to make America greater and greater, again and again.
— We will save the American economy, and make America once again a shining city on the hill.
— Melania promised to decorate the Mexican wall we build on Christmas if I win next elections.
Haters may triumph my new presidency.
